k: 16
sz: 256
LR: 3e-4
BETA1: 0.9
BETA2: 0.999
NUM_GPU: 1
DATASET_ROOT: "../../Downloads/MSCOCO"
IMG_SIZE: 256
BATCH_SIZE: 24
EPOCHS: 32
LAMBDA: 10
SCHEDULER_STEP: 24
SCHEDULER_GAMMA: 0.1
VISUALIZE_STEP: 500
SHUFFLE: True
NUM_WORKERS: 4
CKPT_DIR: "./ckpts"
INIT_FROM: null
PROJECT_NAME: "neural-preset-pytorch"
LOG_DIR: "./logs"
ENTITY: "vvgl-ozu"